# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d2219506ce17eb3397d57531883ba79047ca76888db1a541441b093ca21917783b1bf2ff9afa359b26ea50052356d8d3191db7f6da6516655a647a9655454d

test:
  secret_key_base: e4bcd7d30ef22e3f409c6a96f72a1b9bfda75973857edf75e0448ac2e5a774e5aaacd8fe45c2eb295b71a080145bf86905fa4934fe5689559c6d771d922da7b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
